name: Avtomatika Radarjev

on:
  schedule:
    - cron: '*/10 * * * *'  # Zažene se samodejno vsakih 10 minut
  workflow_dispatch:        # Gumb za ročni zagon

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run robot
        run: python radar.py

      - name: Save data
        run: |
          git config --global user.name "RadarBot"
          git config --global user.email "bot@radar.si"
          git add radarji.json
          git commit -m "Osvežitev podatkov" || exit 0
          git push
