name: Radar Robot Update
on:
  schedule:
    - cron: '*/15 * * * *' # Vsakih 15 minut
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout koda
        uses: actions/checkout@v2
      
      - name: Nastavi Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Namesti knjižnice
        run: pip install requests
        
      - name: Zaženi robota
        run: python robot.py
        
      - name: Objavi spremembe
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add radarji.json
          git commit -m "Robot: Osvežil bazo (Waze/Dars)" || exit 0
          git push
